# Generated by Django 4.0.6 on 2022-08-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='event',
        ),
    ]
